spring.application.name=user-service
spring.datasource.url=jdbc:mysql://localhost:3306/user_db?createDatabaseIfNotExist=true
spring.datasource.username=root
<<<<<<< HEAD
spring.datasource.password=Shravani@28
=======
spring.datasource.password=root
>>>>>>> 089c3f8e9ca150b32ba7bca8f1d7b23b5ffe5b6a

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
<<<<<<< HEAD
spring.redis.host=localhost
spring.redis.port=6379
=======

>>>>>>> 089c3f8e9ca150b32ba7bca8f1d7b23b5ffe5b6a
server.port=8081
